### ISSUE TITLE
Replace cudatoolkit-dev with nvcc package

### ISSUE THREAD

**Issue by bnemanich** [open-ce/tensorrt-feedstock#5]
Remove instances of cudatoolkit-dev from recipes. It should be replaced with `{{ compiler('cuda')}}` inside of the `build` section.

If CUDA_HOME is being set in the build.sh file, it will need to be removed.

**Comment by jayfurmanek** [comment]
The tensorrt-samples package is the tricky part since it requires the cudatoolkit-dev at run time.

**Comment by bnemanich** [comment]
I think it probably makes sense to have activate scripts that check for the availability of CUDA. Since the nvcc package is already doing this, it might be enough to just list that as a dependency.
